[INPUT]
W = "FORWARD"
S = "BACKWARD"
D = "RIGHT"
A = "LEFT"
E = "ROLL_RIGHT"
Q = "ROLL_LEFT"
J = "JUMP"
Shift = "POWERSLIDE"
K = "BOOST"
Space = "TARGET_CAM"
Tab = "SWITCH_TARGET"
Enter = "SWITCH_CAR"
Escape = "FREE_CAM"

[CAMERA]
FOV = 110
DISTANCE = 270
HEIGHT = 110
ANGLE = 3